const DB="pokemonQuestV8",STORE="state";
const APP_VERSION=100;
const THEMES={rosso:{name:"Rosso",strong:"#d63031",soft:"#fff1f1"},rosa:{name:"Rosa",strong:"#e84393",soft:"#fff0f7"},viola:{name:"Viola",strong:"#6c5ce7",soft:"#f2efff"},verde:{name:"Verde",strong:"#00a86b",soft:"#effbf5"},blu:{name:"Blu",strong:"#2878d4",soft:"#eef6ff"},arancione:{name:"Arancione",strong:"#e67e22",soft:"#fff5e9"},oro:{name:"Giallo Oro",strong:"#c79500",soft:"#fff9df"}};
const THEME_KEYS=Object.keys(THEMES);
const L=[
["Bulbasaur","Ivysaur","Venusaur",1,2,3],["Charmander","Charmeleon","Charizard",4,5,6],["Squirtle","Wartortle","Blastoise",7,8,9],
["Treecko","Grovyle","Sceptile",252,253,254],["Torchic","Combusken","Blaziken",255,256,257],["Mudkip","Marshtomp","Swampert",258,259,260],
["Chikorita","Bayleef","Meganium",152,153,154],["Cyndaquil","Quilava","Typhlosion",155,156,157],["Totodile","Croconaw","Feraligatr",158,159,160],
["Turtwig","Grotle","Torterra",387,388,389],["Chimchar","Monferno","Infernape",390,391,392],["Piplup","Prinplup","Empoleon",393,394,395],
["Dratini","Dragonair","Dragonite",147,148,149],["Pichu","Pikachu","Raichu",172,25,26],["Cleffa","Clefairy","Clefable",173,35,36],
["Caterpie","Metapod","Butterfree",10,11,12],["Froakie","Frogadier","Greninja",656,657,658],
["Budew","Roselia","Roserade",406,315,407],["Mankey","Primeape","Annihilape",56,57,979],["Rookidee","Corvisquire","Corviknight",821,822,823],
["Aron","Lairon","Aggron",304,305,306],["Litwick","Lampent","Chandelure",607,608,609],
["Goomy","Sliggoo","Goodra",704,705,706],["Ralts","Kirlia","Gardevoir",280,281,282],["Sewaddle","Swadloon","Leavanny",540,541,542],
["Sandile","Krokorok","Krookodile",551,552,553],["Fennekin","Braixen","Delphox",653,654,655]
];
const UNLOCK_POOLS=[[12,13,14,15,16],[17,18,19,20,21],[22,23,24,25,26]];
const UNLOCK_THRESHOLDS=[4,8,12];
const MEDALS=[
 ["first-quest","🌟","Primo passo","Completa la prima Quest"],
 ["quests-50","🎯","Allenatore costante","Completa 50 Quest"],
 ["quests-100","🏅","Allenatore esperto","Completa 100 Quest"],
 ["group-5","🤝","Spirito di squadra","Completa 5 Quest di gruppo"],
 ["group-20","👨‍👩‍👧‍👦","Squadra affiatata","Completa 20 Quest di gruppo"],
 ["week-350","🎁","Settimana in cammino","Raggiungi 350 XP in una settimana"],
 ["week-800","🏆","Settimana perfetta","Raggiungi 800 XP in una settimana"],
 ["evo-1","✨","Prima evoluzione","Fai evolvere un Pokémon"],
 ["level10","⭐","Allenatore Lv.10","Porta un Pokémon al Lv.10"],
 ["level20","🌟","Allenatore Lv.20","Porta un Pokémon al Lv.20"],
 ["level30","🏆","Campione","Porta un Pokémon al Lv.30"],
 ["team-4","🎖️","Prima squadra completa","Porta 4 Pokémon al Lv.30"],
 ["team-8","🏅","Squadra d'élite","Porta 8 Pokémon al Lv.30"],
 ["team-12","👑","Maestro della squadra","Porta 12 Pokémon al Lv.30"],
 ["discover-1","🔎","Esploratore","Scopri un nuovo Pokémon"],
 ["discover-6","📖","Collezionista","Scopri tutti i 6 nuovi Pokémon"],
 ["pokedex-18","📚","Pokédex completo","Scopri tutti i 18 Pokémon"]
];
function awardMedal(k,id){k.medals=Array.isArray(k.medals)?k.medals:[];if(!k.medals.includes(id))k.medals.push(id)}
function level30Count(k){return (k.unlocked||Array.from({length:L.length},(_,i)=>i)).filter(i=>lvl(Number(k.pokeXp?.[i]||0))>=30).length}
function discoveredCount(k){return (k.unlocked||[]).length}
function pendingStage(k){return Number(k.pendingUnlockStage||0)}
function maybeUnlock(k){const n=level30Count(k);let stage=pendingStage(k);if(stage)return stage;for(let i=0;i<UNLOCK_THRESHOLDS.length;i++){if(n>=UNLOCK_THRESHOLDS[i]&&!k.unlockDone?.[i]){k.pendingUnlockStage=i+1;return i+1}}return 0}
function nextUnlock(k){const n=level30Count(k);return UNLOCK_THRESHOLDS.findIndex(t=>n<t)+1||0}
function checkMedals(k){const q=Number(k.stats?.quests||0),g=Number(k.stats?.groups||0),n=level30Count(k),d=discoveredCount(k);if(q>=1)awardMedal(k,"first-quest");if(q>=50)awardMedal(k,"quests-50");if(q>=100)awardMedal(k,"quests-100");if(g>=5)awardMedal(k,"group-5");if(g>=20)awardMedal(k,"group-20");if(k.weekly>=350)awardMedal(k,"week-350");if(k.weekly>=800)awardMedal(k,"week-800");if((k.evolvedCount||0)>0)awardMedal(k,"evo-1");for(const [id,min] of [["level10",10],["level20",20],["level30",30]])if((k.unlocked||[]).some(i=>lvl(Number(k.pokeXp?.[i]||0))>=min))awardMedal(k,id);if(n>=4)awardMedal(k,"team-4");if(n>=8)awardMedal(k,"team-8");if(n>=12)awardMedal(k,"team-12");if(d>=13)awardMedal(k,"discover-1");if(d>=18)awardMedal(k,"discover-6");if(d>=18)awardMedal(k,"pokedex-18")}
const P=[
[1,2,[["🧸","Metti a posto un gioco"],["🪥","Lavati i denti con un adulto"],["👕","Metti via un vestito"],["👟","Metti le scarpe al loro posto"],["❤️","Fai un piccolo aiuto in casa"]]],
[3,4,[["🧸","Metti a posto i giochi"],["🪥","Lavati i denti"],["👟","Metti le scarpe al loro posto"],["🧺","Metti i vestiti nel cesto"],["🧹","Aiuta a riordinare una stanza"],["❤️","Fai un piccolo aiuto senza che te lo chiedano"]]],
[5,6,[["❤️","Aiuta in casa"],["🧸","Riordina tutti i giochi"],["🪥","Lavati i denti senza essere ricordato"],["👟","Sistema scarpe e giacca"],["🧺","Metti i tuoi vestiti nel cesto"],["🧹","Riordina ciò che hai usato"],["📚","Guarda/leggi un libro per almeno 10 minuti"],["🤝","Aiuta un fratello o una sorella"],["🌱","Prenditi cura di una pianta o di un piccolo compito"]]],
[7,8,[["🧹","Riordina ciò che hai usato"],["📚","Leggi per almeno 15 minuti"],["🧺","Metti a posto i tuoi vestiti"],["🧸","Riordina la tua stanza"],["❤️","Aiuta un familiare senza che te lo chiedano"],["🤝","Fai un gesto gentile verso un fratello/sorella"],["🌱","Svolgi una piccola responsabilità domestica"]]],
[9,10,[["🧹","Riordina ciò che hai usato"],["📚","Leggi per almeno 20 minuti"],["❤️","Aiuta qualcuno senza che te lo chieda"],["🛏️","Riordina la camera"],["🤝","Aiuta un fratello/sorella in una difficoltà"],["🌱","Svolgi una responsabilità domestica"],["📖","Racconta a un adulto qualcosa che hai imparato"]]],
[11,14,[["📚","Leggi per almeno 20 minuti"],["❤️","Aiuta qualcuno senza che te lo chieda"],["⏱️","Gestisci 20 minuti di studio/attività"],["🧹","Svolgi una responsabilità domestica"],["🛏️","Mantieni in ordine la camera"],["🤝","Collabora con un fratello/sorella"],["📖","Racconta o annota una cosa nuova che hai imparato"],["🌱","Svolgi una responsabilità domestica assegnata"],["💡","Proponi un modo per migliorare un'attività di casa"],["🗓️","Controlla da solo gli impegni del giorno dopo"]]]
];
const GROUPS=[
["🧸","Riordinare insieme la cameretta",30],["🛋️","Riordinare insieme il salone",30],["🧹","Fare insieme una piccola pulizia della casa",30],["🧺","Raccogliere e sistemare insieme i giochi",30],["🍽️","Preparare insieme la tavola per un pasto",30],["🍕","Aiutare insieme a preparare la cena",30],["🧩","Fare un gioco da tavolo tutti insieme",30],["🎨","Fare un disegno o lavoretto insieme",30],["🧱","Costruire qualcosa insieme con LEGO o costruzioni",30],["📖","Leggere insieme una storia",30],["🎭","Inventare e mettere in scena una piccola storia",30],["🧩","Fare un puzzle insieme",30],["🔎","Fare una piccola caccia al tesoro in casa",30],["⚽","Giocare insieme all'aperto",30],["🎵","Fare insieme 15 minuti di musica o canto",30],["🧹","Sistemare insieme una zona della casa scelta dai genitori",30],["❤️","Fare qualcosa di gentile per un altro membro della famiglia",30],["🌱","Fare giardinaggio insieme",30],["🏡","Riordinare il cortile insieme",30]
];
let db,s,active,tab="quests";
const $=s=>document.querySelector(s);
const img=id=>`https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${String(id).padStart(3,"0")}.png`;
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const lvl=x=>Math.min(30,Math.floor(x/100)+1),st=l=>l>=20?2:l>=10?1:0;
const pokeXP=k=>Number(k.pokeXp?.[k.line]||0);
const ensurePokeXP=k=>{if(!Array.isArray(k.pokeXp)){const old=Number(k.xp)||0;k.pokeXp=L.map(()=>0);k.pokeXp[Math.max(0,Math.min(L.length-1,Number(k.line)||0))]=old;}else if(k.pokeXp.length<L.length){k.pokeXp=k.pokeXp.concat(Array(L.length-k.pokeXp.length).fill(0));}else if(k.pokeXp.length>L.length){k.pokeXp=k.pokeXp.slice(0,L.length);}k.pokeXp=k.pokeXp.map(x=>Math.max(0,Math.min(3000,Number(x)||0)));k.xp=pokeXP(k);};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function pool(a){return(P.find(x=>a>=x[0]&&a<=x[1])||P[4])[2]}
function xpForText(t){let x=String(t).toLowerCase();if(/20 minuti|20 min|studio|attività fisica|caccia al tesoro|rompicapo/.test(x))return 20;if(/15 minuti|15 min|senza distrazioni|autonomamente|senza che te lo chied/.test(x))return 15;if(/10 minuti|10 min|leggi|leggere|libro|impara|imparato|organizza|responsabilità/.test(x))return 10;return 5}
function ageXP(k,q){
 const base=xpForText(q?.text||"");
 const age=Math.max(1,Math.min(14,Number(k?.age)||7));
 if(age<=2)return 5;
 if(age<=4)return base>=15?10:5;
 if(age<=6)return base>=20?15:(base>=10?10:5);
 if(age<=8)return base>=15?15:(base>=10?10:5);
 if(age<=10)return base;
 return base;
}
const FIXED=[
 {icon:"🎒",text:"Prepara la borsa per il giorno dopo",xp:10},
 {icon:"👕",text:"Preparati e vestiti prima di andare a scuola",xp:10},
 {icon:"🛏️",text:"Fai il letto",xp:5},
 {icon:"👚",text:"Prepara i vestiti per il giorno dopo",xp:10},
 {icon:"🧹",text:"Fai il servizio del tuo turno",xp:15}
];
const ROTATION_TERMS=/apparecchia|sparecchia|svuota la lavastoviglie|svuotare la lavastoviglie|servizio del tuo turno|preparare la tavola|prepara la tavola/;
function isFixed(q){return FIXED.some(f=>f.text===q.text)}
function isRotation(q){return ROTATION_TERMS.test(String(q.text).toLowerCase())}

function weekKey(d=today()){const x=new Date(d+"T12:00:00");const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x.toISOString().slice(0,10)}
function groupQuest(){return s.groupLib?.find(q=>q.id===s.group.qid)||null}
function groupDone(k){return !!k.groupDone?.[today()]}
function groupCard(k){const q=groupQuest();if(!q||s.kids.length<2)return "";const done=groupDone(k),count=s.kids.filter(x=>groupDone(x)).length;return `<div class="card group-card"><div class="row between"><h2>👨‍👩‍👧‍👦 Missione di squadra</h2><span class="chip">${count}/${s.kids.length}</span></div><div class="quest ${done?"done":""}"><span class="icon">${q.icon}</span><span class="text">${esc(q.text)} <span class="small">+30 XP</span></span><button data-gq="${q.id}">${done?"↩️ Annulla":"🤝 Fatto"}</button></div><div class="small">Una sola missione di gruppo al giorno, senza ripetizioni nella stessa settimana.</div></div>`}
function combinations(items,n,target,start=0,picked=[],out=[]){if(out.length)return out;if(n===0){if(target===0)out.push(picked.slice());return out}for(let i=start;i<=items.length-n;i++){let v=items[i].xp;if(v>target)continue;combinations(items,n-1,target-v,i+1,picked.concat(items[i]),out);if(out.length)break}return out}
function variableCandidates(k){return assigned(k).filter(q=>!isRotation(q)&&!isFixed(q)).map(q=>({q,xp:Math.max(5,Math.min(20,ageXP(k,q)))}))}
function minFiveXP(k){let a=variableCandidates(k).map(x=>x.xp).sort((x,y)=>x-y);return a.length>=5?a.slice(0,5).reduce((a,b)=>a+b,0):0}
function commonDailyTarget(){if(!s.kids.length)return 0;return Math.max(...s.kids.map(minFiveXP))}
function balancedFive(k,target){let vars=variableCandidates(k);if(vars.length<5)return [];vars.sort((a,b)=>a.xp-b.xp||a.q.text.localeCompare(b.q.text));let best=null;for(let i=0;i<vars.length;i++)for(let j=i+1;j<vars.length;j++)for(let h=j+1;h<vars.length;h++)for(let m=h+1;m<vars.length;m++)for(let n=m+1;n<vars.length;n++){let chosen=[vars[i],vars[j],vars[h],vars[m],vars[n]];let base=chosen.reduce((a,x)=>a+x.xp,0);if(base>target)continue;let cap=chosen.reduce((a,x)=>a+(20-x.xp),0);if(base+cap<target)continue;let need=target-base;let xs=chosen.map(x=>x.xp);for(let z=0;z<xs.length&&need>0;z++){let add=Math.min(20-xs[z],need);add-=add%5;xs[z]+=add;need-=add}if(need===0){let score=base; if(!best||score>best.base)best={chosen,xs,base};}}return best?best.chosen.map((x,i)=>({q:x.q,xp:best.xs[i]})):[]}
function dailyPlan(k){let cache=k.dailyPlan?.[today()];if(Array.isArray(cache)&&cache.length===5&&cache.every(x=>s.lib.some(q=>q.id===x.id))){let total=cache.reduce((a,x)=>a+Number(x.xp||0),0),target=commonDailyTarget();if(total===target)return cache.map(x=>({q:s.lib.find(q=>q.id===x.id),xp:Number(x.xp)}))}let target=commonDailyTarget(),result=balancedFive(k,target);if(result.length<5){let vars=variableCandidates(k).slice().sort((a,b)=>a.xp-b.xp||a.q.text.localeCompare(b.q.text));result=vars.slice(0,5).map(x=>({q:x.q,xp:x.xp}));}k.dailyPlan=k.dailyPlan||{};k.dailyPlan[today()]=result.map(x=>({id:x.q.id,xp:x.xp}));return result}
function dailyQs(k){let fixed=FIXED.map(f=>{let q=s.lib.find(x=>x.text===f.text);if(!q){q={id:id(),...f};s.lib.push(q)}else{q.icon=f.icon;q.xp=f.xp}return q});return fixed.concat(dailyPlan(k).map(x=>x.q));}
function dailyXP(k,q){let f=FIXED.find(x=>x.text===q.text);if(f)return f.xp;return dailyPlan(k).find(x=>x.q?.id===q.id)?.xp ?? Math.max(5,Math.min(20,ageXP(k,q)));}
function kid(n,a,theme="viola",avatar="none"){return{id:id(),name:n,age:a,xp:0,weekly:0,weekKey:weekKey(),line:0,dailyBonus:{},theme:THEME_KEYS.includes(theme)?theme:"viola",avatar:avatar||"none",done:{},unlocked:Array.from({length:12},(_,i)=>i),unlockDone:{},pendingUnlockStage:0,stats:{quests:0,groups:0},medals:[],evolvedCount:0,evolutionForms:{}}}
function open(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
function get(){return new Promise((ok,no)=>{let r=db.transaction(STORE).objectStore(STORE).get("s");r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function save(){return new Promise((ok,no)=>{let r=db.transaction(STORE,"readwrite").objectStore(STORE).put(s,"s");r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function init(){s={version:0,pin:"1234",kids:[kid("Giuseppe",9,"rosso"),kid("Anna Chiara",7,"rosa"),kid("Elisabetta",5,"viola"),kid("Miriam",2,"verde")],lib:[],assign:{},groupLib:GROUPS.map(([icon,text,xp])=>({id:id(),icon,text,xp})),group:{date:today(),qid:null,done:{}},groupHistory:{},reward:{small:350,big:800}};seedApprovedPools();ensure()}
function seedApprovedPools(){const texts=[...new Set(P.flatMap(x=>x[2].map(y=>y[1])))];for(const [icon,text] of P.flatMap(x=>x[2])){if(!s.lib.some(q=>q.text===text))s.lib.push({id:id(),icon,text,xp:xpForText(text)})}for(const k of s.kids){s.assign[k.id]=s.assign[k.id]||[];for(const text of texts){let q=s.lib.find(x=>x.text===text);if(q&&!s.assign[k.id].includes(q.id))s.assign[k.id].push(q.id)}}}
function ensure(){
 s=s||{};const oldVersion=Number(s.version)||0;s.version=APP_VERSION;s.pin=s.pin||"1234";s.kids=Array.isArray(s.kids)?s.kids:[];s.lib=Array.isArray(s.lib)?s.lib:[];s.assign=s.assign&&typeof s.assign==="object"?s.assign:{};s.reward={small:350,big:800};s.groupLib=Array.isArray(s.groupLib)?s.groupLib:GROUPS.map(([icon,text,xp])=>({id:id(),icon,text,xp}));s.groupLib.forEach(q=>q.xp=30);s.group=s.group&&typeof s.group==="object"?s.group:{date:today(),qid:null,done:{}};s.group.done=s.group.done&&typeof s.group.done==="object"?s.group.done:{};s.groupHistory=s.groupHistory&&typeof s.groupHistory==="object"?s.groupHistory:{};
 if(!s.kids.length)s.kids=[kid("Giuseppe",9,"rosso"),kid("Anna Chiara",7,"rosa"),kid("Elisabetta",5,"viola"),kid("Miriam",2,"verde")];
 const oldTexts=new Set(["Lavati le mani","Porta il tuo bicchiere a tavola","Metti un pupazzo al suo posto","Metti un oggetto nel suo cesto","Vestiti da solo","Lavati le mani prima di mangiare","Porta il tuo piatto a tavola","Metti il bicchiere al suo posto","Sistema il cuscino o il letto","Metti a posto il pigiama","Prepara una cosa per domani","Prepara i vestiti per domani","Aiuta a preparare la tavola","Lascia in ordine il bagno dopo averlo usato","Prepara zaino e materiale","Sistema il letto","Apparecchia o sparecchia la tavola","Metti a posto il bagno dopo averlo usato"]);
 if(oldVersion<APP_VERSION){const removedGroups=new Set(["Mettere in ordine insieme libri e materiale scolastico","Preparare insieme la colazione","Fare una passeggiata insieme"]);s.groupLib=s.groupLib.filter(q=>!removedGroups.has(q.text));const old=s.groupLib.find(q=>q.text==="Risolvere insieme un enigma o rompicapo");if(old){old.text="Fare un puzzle insieme";old.icon="🧩";old.xp=30}[ ["🌱","Fare giardinaggio insieme"],["🏡","Riordinare il cortile insieme"] ].forEach(([icon,text])=>{if(!s.groupLib.some(q=>q.text===text))s.groupLib.push({id:id(),icon,text,xp:30})});for(const k of s.kids){k.dailyPlan={};}}
 if(oldVersion<90){for(const k of s.kids)k.dailyPlan={};}
 s.kids.forEach(k=>{
  k.age=Math.max(1,Math.min(14,Number(k.age)||7));k.theme=THEME_KEYS.includes(k.theme)?k.theme:"viola";k.avatar=k.avatar||"none";k.dailyBonus=k.dailyBonus&&typeof k.dailyBonus==="object"?k.dailyBonus:{};k.groupDone=k.groupDone&&typeof k.groupDone==="object"?k.groupDone:{};k.xp=Number(k.xp)||0;k.weekly=Number(k.weekly)||0;k.weekKey=k.weekKey||weekKey();
  if(k.weekKey!==weekKey()){k.weekly=0;k.weekKey=weekKey();k.dailyBonus={};}
  k.line=Math.max(0,Math.min(L.length-1,Number(k.line)||0));ensurePokeXP(k);k.done=k.done&&typeof k.done==="object"?k.done:{};k.dailyPlan=k.dailyPlan&&typeof k.dailyPlan==="object"?k.dailyPlan:{};s.assign[k.id]=Array.isArray(s.assign[k.id])?s.assign[k.id]:[];
  k.unlocked=Array.isArray(k.unlocked)?[...new Set(k.unlocked.map(Number).filter(i=>i>=0&&i<L.length))]:Array.from({length:12},(_,i)=>i);for(let i=0;i<12;i++)if(!k.unlocked.includes(i))k.unlocked.push(i);k.unlocked.sort((a,b)=>a-b);
  k.unlockDone=k.unlockDone&&typeof k.unlockDone==="object"?k.unlockDone:{};k.pendingUnlockStage=Number(k.pendingUnlockStage)||0;k.stats=k.stats&&typeof k.stats==="object"?k.stats:{};k.stats.quests=Number(k.stats.quests)||0;k.stats.groups=Number(k.stats.groups)||0;k.medals=Array.isArray(k.medals)?k.medals:[];k.evolvedCount=Number(k.evolvedCount)||0;k.evolutionForms=k.evolutionForms&&typeof k.evolutionForms==="object"?k.evolutionForms:{};
  if(k._new){for(const pair of pool(k.age)){const [icon,text]=pair;if(!s.lib.some(q=>q.text===text))s.lib.push({id:id(),icon,text,xp:xpForText(text)});const q=s.lib.find(x=>x.text===text);if(q&&!s.assign[k.id].includes(q.id))s.assign[k.id].push(q.id)}delete k._new;}
  FIXED.forEach(f=>{let q=s.lib.find(x=>x.text===f.text);if(!q){q={id:id(),...f};s.lib.push(q)}else{q.icon=f.icon;q.xp=f.xp}if(!s.assign[k.id].includes(q.id))s.assign[k.id].push(q.id)});
  // Recover counters from existing completion data where possible.
  if(!k.stats.quests)k.stats.quests=Object.keys(k.done).filter(x=>x.endsWith("|earned")).length;
  if(!k.stats.groups)k.stats.groups=Object.keys(k.groupDone).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).length;
  // If old data already has enough Lv.30 Pokémon, make the corresponding unlock choices available.
  maybeUnlock(k);checkMedals(k);
 });
 if(s.group.date!==today()){s.group.date=today();s.group.qid=null;s.group.done={}}if(!s.group.qid&&s.groupLib.length){let used=Object.entries(s.groupHistory).filter(([d])=>weekKey(d)===weekKey()).map(([,q])=>q);let choices=s.groupLib.filter(q=>!used.includes(q.id));if(!choices.length)choices=s.groupLib.slice();let seed=[...today()].reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),13);s.group.qid=choices[seed%choices.length].id;s.groupHistory[today()]=s.group.qid}
}
async function boot(){
 try{await open();s=await get();if(!s)init();ensure();await save();active=s.kids[0]?.id||null;render()}
 catch(e){console.error(e);$("#app").innerHTML=`<div class="card"><h2>⚠️ Errore di caricamento</h2><p>Il browser ha bloccato il salvataggio locale.</p><p class="small">${esc(e?.message||e)}</p><button onclick="location.reload()">Ricarica</button></div>`}
}
function assigned(k){return(s.assign[k.id]||[]).map(x=>s.lib.find(q=>q.id===x)).filter(Boolean)}
function done(k,q){return!!k.done[today()+"|"+q.id]}
function weeklyBar(k,target){const v=Math.min(target,Number(k.weekly)||0);return `<div class="progress big-progress"><div class="bar" style="width:${Math.min(100,v/target*100)}%"></div></div><div class="row between"><span class="small">${v} / ${target} XP</span><span class="small">${v>=target?"✓ Raggiunto":""}</span></div>`}
function progressCard(k){const n=level30Count(k),next=UNLOCK_THRESHOLDS.find(t=>n<t);const d=discoveredCount(k);return `<div class="card progress-section"><h3>🎯 Obiettivi della settimana</h3><div class="weekly-goal"><div class="row between"><b>🎁 Piccola ricompensa</b><span class="chip">350 XP</span></div>${weeklyBar(k,350)}</div><div class="weekly-goal"><div class="row between"><b>🏆 Grande ricompensa</b><span class="chip">800 XP</span></div>${weeklyBar(k,800)}</div><div class="small">La settimana va da lunedì a domenica. I progressi di questa sezione si azzerano all'inizio della nuova settimana.</div></div><div class="card progress-section"><h3>🏆 Addestramento della squadra</h3><div class="row between"><b>${n} Pokémon al Lv.30</b><span class="chip">${next?`${n}/${next}`:"12+ completati"}</span></div>${next?`<div class="progress big-progress"><div class="bar" style="width:${Math.min(100,n/next*100)}%"></div></div><div class="small">${next-n===1?"Ancora 1 Pokémon":`Ancora ${next-n} Pokémon`} al Lv.30 per una nuova scoperta.</div>`:`<div class="progress big-progress"><div class="bar" style="width:100%"></div></div><div class="small">Hai raggiunto tutti i traguardi di sblocco!</div>`}</div><div class="card progress-section"><div class="row between"><h3>📖 Pokédex</h3><span class="chip">${d}/${L.length}</span></div><div class="progress big-progress"><div class="bar" style="width:${d/L.length*100}%"></div></div><div class="small">Ogni nuova creatura scoperta entra nel tuo Pokédex e resta conquistata.</div></div><div class="card progress-section"><div class="row between"><h3>🏅 Medagliere</h3><span class="chip">${k.medals.length}/${MEDALS.length}</span></div><div class="medal-grid">${MEDALS.map(m=>{const won=k.medals.includes(m[0]);return `<div class="medal ${won?"won":"locked"}"><div class="medal-icon">${won?m[1]:"🔒"}</div><b>${won?m[2]:"Medaglia misteriosa"}</b><div class="small">${won?m[3]:"Continua il tuo allenamento per scoprirla."}</div></div>`}).join("")}</div></div>`}
function evolutionNoticeHtml(){if(!window.evoNotice)return "";const e=window.evoNotice;return `<div class="evo-overlay"><div class="evo-box"><div class="evo-title">✨ EVOLUZIONE!</div><img class="evo-old" src="${img(e.oldId)}"><span class="evo-arrow">→</span><img class="evo-new" src="${img(e.newId)}"><div><b>${e.oldName} → ${e.newName}</b></div></div></div>`}
function unlockOverlay(k){const stage=pendingStage(k);if(!stage)return "";const poolIds=UNLOCK_POOLS[stage-1];return `<div class="unlock-overlay"><div class="unlock-box"><div class="unlock-title">🎉 NUOVE CREATURE DA SCOPRIRE!</div><p>Hai raggiunto ${UNLOCK_THRESHOLDS[stage-1]} Pokémon al Lv.30.</p><p><b>Scegli 2 Pokémon tra questi 5.</b></p><div class="unlock-grid">${poolIds.map(i=>{const p=L[i];return `<label class="unlock-option"><input type="checkbox" class="unlock-choice" value="${i}"><img src="${img(p[3])}"><b>${p[0]}</b><span class="small">${p[1]} → ${p[2]}</span></label>`}).join("")}</div><div class="row between"><span class="small">Scegli esattamente 2.</span><button id="confirmUnlock" disabled>🔓 Conferma scelta</button></div></div></div>`}
function render(){
 const k=s.kids.find(x=>x.id===active);if(!k){$("#app").innerHTML="";return}
 let currentXP=pokeXP(k),l=lvl(currentXP),z=st(l),p=L[k.line];
 let tabs=s.kids.map(x=>`<button class="kid-tab theme-${x.theme} ${x.id===active?"active":""}" data-k="${x.id}">${x.avatar&&x.avatar!=="none"?esc(x.avatar)+" ":""}${esc(x.name)}</button>`).join("");
 let html=`<div class="kids">${tabs}</div><div class="theme-page ${k.age<=6?"simple":""}" style="--theme:${THEMES[k.theme].strong};--theme-soft:${THEMES[k.theme].soft}"><div class="card hero"><img src="${img(p[3+z])}"><div><div class="row between"><b class="theme-name" style="font-size:1.3rem">${p[z]}</b><span class="chip">Lv ${l}</span></div><div class="small">${p[0]} → ${p[1]} → ${p[2]}</div><div class="progress"><div class="bar" style="width:${currentXP%100}%"></div></div><div class="row"><span class="chip">⭐ ${currentXP} XP</span><span class="chip">📅 ${k.weekly} XP</span></div></div></div><div class="tabs"><button class="${tab==="quests"?"active":""}" data-t="quests">${k.age<=6?"⭐ Le mie missioni":"📜 Quest"}</button><button class="${tab==="pokemon"?"active":""}" data-t="pokemon">⚡ Pokémon</button><button class="${tab==="progress"?"active":""}" data-t="progress">🏆 Progressi</button></div>${pane(k)}</div></div>${unlockOverlay(k)}${evolutionNoticeHtml()}`;
 $("#app").innerHTML=html;bind();
}
function speakQuest(text){if(!( "speechSynthesis" in window)){alert("La lettura vocale non è disponibile su questo dispositivo.");return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang="it-IT";u.rate=.9;speechSynthesis.speak(u)}
function pokeCard(k,i){const p=L[i],x=Number(k.pokeXp?.[i]||0),lv=lvl(x),form=st(lv),selected=i===k.line;return `<div class="poke-card ${selected?"selected":""}"><img src="${img(p[3+form])}"><div class="row between"><b>${p[form]}</b><span class="chip">Lv ${lv}</span></div><div class="small">${p[0]} → ${p[1]} → ${p[2]}</div><div class="progress"><div class="bar" style="width:${lv>=30?100:x%100}%"></div></div><div class="small">${Math.min(x,3000)} / 3000 XP</div><button data-p="${i}">${selected?"✓ Selezionato":"Scegli"}</button></div>`}
function pane(k){
 if(tab==="quests"){let qs=dailyQs(k),doneN=qs.filter(q=>done(k,q)).length;if(k.age<=6)return `<div class="pane active card"><div class="row between"><h2>⭐ Missioni</h2><span class="chip">${doneN}/${qs.length}</span></div><p class="small">Tocca 🔊 per ascoltare la missione.</p>${qs.map(q=>{let d=done(k,q);return `<div class="quest ${d?"done":""}"><span class="icon">${q.icon}</span><span class="text">${esc(q.text)} <span class="small">+${q.xp??10} XP</span></span><button data-speak="${esc(q.text)}">🔊</button><button data-q="${q.id}">${d?"↩️":"✅"}</button></div>`}).join("")}<div class="small">10 missioni al giorno. I punti dipendono dalla difficoltà e dal tempo richiesto. Completandole tutte ottieni il bonus di completamento della giornata, senza XP extra.</div>${groupCard(k)}</div>`;return `<div class="pane active card"><div class="row between"><h2>Quest di oggi</h2><span class="chip">${doneN}/${qs.length}</span></div>${qs.map(q=>{let d=done(k,q);return `<div class="quest ${d?"done":""}"><span class="icon">${q.icon}</span><span class="text">${esc(q.text)} <span class="small">+${q.xp??10} XP</span></span><button data-q="${q.id}">${d?"↩️ Annulla":"✅ Fatto"}</button></div>`}).join("")}<div class="small">10 Quest al giorno. Ogni Quest vale XP diversi in base alla difficoltà/tempo. Completandole tutte ottieni il bonus di completamento della giornata, senza XP extra.</div>${groupCard(k)}</div>`}
 if(tab==="pokemon"){const unlocked=(k.unlocked||[]);return `<div class="pane active card"><div class="row between"><div><h2>⚡ La mia squadra</h2><p class="small">Tocca un Pokémon per sceglierlo per le prossime Quest.</p></div><span class="chip">${unlocked.length}/${L.length}</span></div><div class="poke-grid">${unlocked.map(i=>pokeCard(k,i)).join("")}${Array.from({length:L.length-unlocked.length},()=>`<div class="poke-card locked-poke"><div class="lock-symbol">🔒</div><b>Nuova creatura</b><div class="small">Continua ad allenarti per scoprirla.</div></div>`).join("")}</div></div>`}
 return `<div class="pane active">${progressCard(k)}</div>`;
}
function evolutionForGain(k,line,oldXP,newXP){const oldL=lvl(oldXP),newL=lvl(newXP);for(let threshold of [10,20]){if(oldL<threshold&&newL>=threshold){const oldForm=threshold===10?0:1,newForm=threshold===10?1:2;window.evoNotice={oldId:L[line][3+oldForm],newId:L[line][3+newForm],oldName:L[line][oldForm],newName:L[line][newForm]};k.evolvedCount=(k.evolvedCount||0)+1;k.evolutionForms[line]=newForm;return true}}return false}
function afterXP(k){maybeUnlock(k);checkMedals(k);}
function bind(){
 document.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{active=b.dataset.k;tab="quests";render()});
 document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{tab=b.dataset.t;render()});
 document.querySelectorAll("[data-p]").forEach(b=>b.onclick=async()=>{let kk=s.kids.find(k=>k.id===active),i=+b.dataset.p;if(!kk.unlocked.includes(i))return;kk.line=i;kk.xp=pokeXP(kk);await save();render()});
 document.querySelectorAll("[data-speak]").forEach(b=>b.onclick=()=>speakQuest(b.dataset.speak));
 bindGroup();
 document.querySelectorAll("[data-q]").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===active),q=s.lib.find(x=>x.id===b.dataset.q),key=today()+"|"+q.id,d=!!k.done[key];let qs=dailyQs(k),base=dailyXP(k,q);if(d){let earned=Number(k.done[key+"|earned"]||base),earnedLine=Number(k.done[key+"|line"]??k.line);delete k.done[key];delete k.done[key+"|earned"];delete k.done[key+"|line"];k.pokeXp[earnedLine]=Math.max(0,Number(k.pokeXp[earnedLine]||0)-earned);k.xp=pokeXP(k);k.weekly=Math.max(0,k.weekly-earned);let remaining=qs.filter(x=>done(k,x)).length,bonus=Number(k.dailyBonus?.[today()]||0);if(bonus&&remaining<qs.length){let bonusLine=Number(k.dailyBonus?.[today()+"|line"]??k.line);k.pokeXp[bonusLine]=Math.max(0,Number(k.pokeXp[bonusLine]||0)-bonus);k.xp=pokeXP(k);k.weekly=Math.max(0,k.weekly-bonus);delete k.dailyBonus[today()];delete k.dailyBonus[today()+"|line"]}}else{let earnedLine=k.line,oldXP=pokeXP(k),newXP=Math.min(3000,oldXP+base);k.done[key]=1;k.done[key+"|earned"]=base;k.done[key+"|line"]=earnedLine;k.pokeXp[earnedLine]=newXP;k.xp=pokeXP(k);k.weekly+=base;k.stats.quests=(k.stats.quests||0)+1;evolutionForGain(k,earnedLine,oldXP,newXP);let all=qs.length>0&&qs.every(x=>done(k,x));if(all){k.dailyBonus[today()]=1;k.dailyBonus[today()+"|line"]=k.line}}afterXP(k);await save();render();if(window.evoNotice)setTimeout(()=>{window.evoNotice=null;render()},3200)});
 document.querySelectorAll("#confirmUnlock").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===active),stage=pendingStage(k),chosen=[...document.querySelectorAll(".unlock-choice:checked")].map(x=>+x.value);if(chosen.length!==2)return;chosen.forEach(i=>{if(!k.unlocked.includes(i))k.unlocked.push(i)});k.unlocked.sort((a,b)=>a-b);k.unlockDone[stage-1]=1;k.pendingUnlockStage=0;awardMedal(k,"discover-1");if(discoveredCount(k)>=18)awardMedal(k,"discover-6");if(discoveredCount(k)>=18)awardMedal(k,"pokedex-18");await save();render()});
 const choices=[...document.querySelectorAll(".unlock-choice")],confirm=$("#confirmUnlock");if(confirm){const sync=()=>{const n=document.querySelectorAll(".unlock-choice:checked").length;confirm.disabled=n!==2;choices.forEach(c=>c.disabled=n>=2&&!c.checked)};choices.forEach(c=>c.onchange=sync);sync()}
}
function bindGroup(){document.querySelectorAll("[data-gq]").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===active),q=groupQuest();if(!k||!q)return;k.groupDone=k.groupDone||{};let xp=30;if(groupDone(k)){let earned=Number(k.groupDone["xp|"+today()]||xp),earnedLine=Number(k.groupDone["line|"+today()]??k.line);delete k.groupDone[today()];delete k.groupDone["xp|"+today()];delete k.groupDone["line|"+today()];k.pokeXp[earnedLine]=Math.max(0,Number(k.pokeXp[earnedLine]||0)-earned);k.xp=pokeXP(k);k.weekly=Math.max(0,k.weekly-earned)}else{let earnedLine=k.line,oldXP=pokeXP(k),newXP=Math.min(3000,oldXP+xp);k.groupDone[today()]=1;k.groupDone["xp|"+today()]=xp;k.groupDone["line|"+today()]=earnedLine;k.pokeXp[earnedLine]=newXP;k.xp=pokeXP(k);k.weekly+=xp;k.stats.groups=(k.stats.groups||0)+1;evolutionForGain(k,earnedLine,oldXP,newXP)}afterXP(k);await save();render();if(window.evoNotice)setTimeout(()=>{window.evoNotice=null;render()},3200)})}
function admin(){let m=$("#modal");m.innerHTML=`<div style="overflow:auto"><div class="row between"><h2>🔐 Area adulti</h2><button id="close">Chiudi</button></div><div class="tabs"><button data-a="kids">👨‍👩‍👧 Bambini</button><button data-a="quests">📜 Quest giornaliere</button><button data-a="groups">👨‍👩‍👧‍👦 Quest di gruppo</button><button data-a="data">💾 Dati</button></div><div id="ab"></div></div>`;m.showModal();$("#close").onclick=()=>m.close();document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>adminPane(b.dataset.a));adminPane("kids")}
function adminPane(t){
 let b=$("#ab");
 if(t==="kids")b.innerHTML=`<div class="card"><button id="add">＋ Aggiungi bambino</button></div>${s.kids.map(k=>`<div class="list"><label>Nome</label><input data-n="${k.id}" value="${esc(k.name)}"><label>Età (fino a 6 = modalità semplificata)</label><input data-age="${k.id}" type="number" min="1" max="14" value="${k.age}"><label>Tema colore</label><select data-theme="${k.id}">${THEME_KEYS.map(t=>`<option value="${t}" ${k.theme===t?"selected":""}>${THEMES[t].name}</option>`).join("")}</select><label>Avatar</label><select data-avatar="${k.id}"><option value="none" ${!k.avatar||k.avatar==="none"?"selected":""}>Nessuno</option><option value="🙂" ${k.avatar==="🙂"?"selected":""}>🙂</option><option value="👧" ${k.avatar==="👧"?"selected":""}>👧</option><option value="👦" ${k.avatar==="👦"?"selected":""}>👦</option><option value="🧒" ${k.avatar==="🧒"?"selected":""}>🧒</option><option value="🐉" ${k.avatar==="🐉"?"selected":""}>🐉</option><option value="⭐" ${k.avatar==="⭐"?"selected":""}>⭐</option><option value="⚡" ${k.avatar==="⚡"?"selected":""}>⚡</option></select><div class="theme-preview" style="background:${THEMES[k.theme].soft};color:${THEMES[k.theme].strong};border-color:${THEMES[k.theme].strong}">Anteprima tema: ${THEMES[k.theme].name}</div><button data-save="${k.id}">Salva</button> <button data-del="${k.id}" style="background:#d63031">Elimina</button></div>`).join("")}`;
 else if(t==="quests")b.innerHTML=`<div class="card"><h3>📜 Quest giornaliere</h3><p class="small">Le Quest personali comprendono 5 attività fisse e 5 variabili ogni giorno.</p><button id="newq">＋ Nuova Quest</button></div><div id="assignPanel"></div>${s.lib.map(q=>`<div class="list"><b>${q.icon} ${esc(q.text)}</b><div class="small">⭐ ${q.xp ?? 10} XP · Assegnata a: ${s.kids.filter(k=>(s.assign[k.id]||[]).includes(q.id)).map(k=>esc(k.name)).join(", ")||"nessuno"}</div><button data-e="${q.id}">Modifica</button><button data-as="${q.id}">Assegna</button><button data-delq="${q.id}" class="danger">🗑️ Elimina</button></div>`).join("")}`;
 else if(t==="groups")b.innerHTML=`<div class="card"><h3>👨‍👩‍👧‍👦 Quest di gruppo</h3><p class="small">Una Quest al giorno, scelta casualmente e senza ripetizioni nella stessa settimana. Ogni bambino riceve gli XP quando la completa.</p><button id="newg">＋ Nuova Quest di gruppo</button></div>${s.groupLib.map(q=>`<div class="list"><b>${q.icon} ${esc(q.text)}</b><div class="small">⭐ 30 XP</div><button data-eg="${q.id}">Modifica</button><button data-dg="${q.id}" class="danger">🗑️ Elimina</button></div>`).join("")}`;
 else b.innerHTML=`<div class="card"><button id="export">Esporta backup JSON</button><input id="import" type="file" accept=".json"><p class="small">Il backup contiene profili, XP, Pokémon, Quest, Quest di gruppo, assegnazioni e impostazioni.</p><hr><input id="pin" type="password" placeholder="Nuovo PIN"><button id="pinb">Cambia PIN</button></div>`;
 bindAdmin();
}

function openAssignPanel(qid){
 let q=s.lib.find(x=>x.id===qid),p=$("#assignPanel");if(!q||!p)return;
 const assignedIds=new Set(s.kids.filter(k=>(s.assign[k.id]||[]).includes(q.id)).map(k=>k.id));
 p.innerHTML=`<div class="assign-card"><div class="row between"><div><h3>👥 Assegna Quest</h3><div class="small">${q.icon} ${esc(q.text)}</div></div><button type="button" class="secondary" id="cancelAssign">Annulla</button></div><label class="check-row all"><input type="checkbox" id="assignAll"> <b>Tutti</b></label><div class="assign-kids">${s.kids.map(k=>`<label class="check-row"><input type="checkbox" class="assignKid" value="${k.id}" ${assignedIds.has(k.id)?"checked":""}> <span>${esc(k.name)}</span></label>`).join("")}</div><div class="row"><button type="button" id="saveAssign">💾 Salva assegnazione</button></div></div>`;
 const all=p.querySelector("#assignAll"),checks=[...p.querySelectorAll(".assignKid")];
 const syncAll=()=>{all.checked=checks.length>0&&checks.every(c=>c.checked);all.indeterminate=checks.some(c=>c.checked)&&!all.checked};
 all.onchange=()=>{checks.forEach(c=>c.checked=all.checked);all.indeterminate=false};checks.forEach(c=>c.onchange=syncAll);syncAll();
 p.querySelector("#cancelAssign").onclick=()=>{p.innerHTML=""};
 p.querySelector("#saveAssign").onclick=async()=>{const selected=new Set(checks.filter(c=>c.checked).map(c=>c.value));s.kids.forEach(k=>{s.assign[k.id]=Array.isArray(s.assign[k.id])?s.assign[k.id]:[];const has=s.assign[k.id].includes(q.id);if(selected.has(k.id)&&!has)s.assign[k.id].push(q.id);if(!selected.has(k.id)&&has)s.assign[k.id]=s.assign[k.id].filter(x=>x!==q.id)});await save();adminPane("quests");render()};
 p.scrollIntoView({behavior:"smooth",block:"nearest"});
}
function bindAdmin(){
 $("#add")?.addEventListener("click",()=>{let n=prompt("Nome?");if(!n)return;let a=Math.max(1,Math.min(14,+prompt("Età (1-14)?","7")||7)),k=kid(n,a,"viola");k._new=true;s.kids.push(k);s.assign[k.id]=[];ensure();save().then(()=>{render();adminPane("kids")})});
 document.querySelectorAll("[data-save]").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===b.dataset.save);k.name=$(`[data-n="${k.id}"]`).value||k.name;k.age=Math.max(1,Math.min(14,+$(`[data-age="${k.id}"]`).value||7));k.theme=$(`[data-theme="${k.id}"]`).value||"viola";k.avatar=$(`[data-avatar="${k.id}"]`).value||"none";s.assign[k.id]=Array.isArray(s.assign[k.id])?s.assign[k.id]:[];ensure();await save();render();adminPane("kids")});
 document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(!confirm("Eliminare il profilo?"))return;let i=b.dataset.del;s.kids=s.kids.filter(k=>k.id!==i);delete s.assign[i];active=s.kids[0]?.id;await save();render();adminPane("kids")});
 $("#newq")?.addEventListener("click",()=>{let tx=prompt("Testo Quest");if(!tx)return;let xv=Math.max(5,Math.min(30,+prompt("XP (5-30)",String(xpForText(tx)))||xpForText(tx)));s.lib.push({id:id(),icon:prompt("Icona","⭐")||"⭐",text:tx,xp:xv});save().then(()=>adminPane("quests"))});
 document.querySelectorAll("[data-e]").forEach(b=>b.onclick=async()=>{let q=s.lib.find(x=>x.id===b.dataset.e),tx=prompt("Testo",q.text);if(tx===null)return;q.text=tx;q.icon=prompt("Icona",q.icon)||q.icon;q.xp=Math.max(5,Math.min(30,+prompt("XP (5-30)",String(q.xp||xpForText(q.text)))||q.xp||xpForText(q.text)));await save();adminPane("quests");render()});
 document.querySelectorAll("[data-as]").forEach(b=>b.onclick=()=>openAssignPanel(b.dataset.as));
 document.querySelectorAll("[data-delq]").forEach(b=>b.onclick=async()=>{let q=s.lib.find(x=>x.id===b.dataset.delq);if(!q)return;if(!confirm(`Eliminare la Quest "${q.text}"?\n\nVerrà rimossa dalla libreria e dalle assegnazioni di tutti i bambini.`))return;s.lib=s.lib.filter(x=>x.id!==q.id);s.kids.forEach(k=>{s.assign[k.id]=(s.assign[k.id]||[]).filter(x=>x!==q.id)});await save();adminPane("quests");render()});
 $("#newg")?.addEventListener("click",()=>{let tx=prompt("Testo Quest di gruppo");if(!tx)return;let xv=30;s.groupLib.push({id:id(),icon:prompt("Icona","🤝")||"🤝",text:tx,xp:xv});save().then(()=>adminPane("groups"))});
 document.querySelectorAll("[data-eg]").forEach(b=>b.onclick=async()=>{let q=s.groupLib.find(x=>x.id===b.dataset.eg);if(!q)return;let tx=prompt("Testo",q.text);if(tx===null)return;q.text=tx;q.icon=prompt("Icona",q.icon)||q.icon;q.xp=30;await save();adminPane("groups");render()});
 document.querySelectorAll("[data-dg]").forEach(b=>b.onclick=async()=>{let q=s.groupLib.find(x=>x.id===b.dataset.dg);if(!q)return;if(s.groupLib.length<=1)return alert("Deve rimanere almeno una Quest di gruppo.");if(!confirm(`Eliminare la Quest di gruppo "${q.text}"?`))return;s.groupLib=s.groupLib.filter(x=>x.id!==q.id);s.groupHistory=Object.fromEntries(Object.entries(s.groupHistory||{}).filter(([,v])=>v!==q.id));if(s.group.qid===q.id)s.group.qid=null;await save();ensure();await save();adminPane("groups");render()});
 $("#export")?.addEventListener("click",()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:"application/json"}));a.download="pokemon-quest-backup.json";a.click()});
 $("#import")?.addEventListener("change",async e=>{let f=e.target.files[0];if(!f)return;try{s=JSON.parse(await f.text());ensure();await save();active=s.kids[0]?.id;render();alert("Backup ripristinato")}catch{alert("Backup non valido")}});
 $("#pinb")?.addEventListener("click",async()=>{let p=$("#pin").value;if(p.length<4)return alert("PIN troppo corto");s.pin=p;await save();alert("PIN cambiato")});
}

$("#adult").onclick=()=>{let m=$("#modal");m.innerHTML=`<h2>🔐 Area adulti</h2><input id="pp" type="password" inputmode="numeric" placeholder="PIN"><p id="err" class="small"></p><button id="go">Accedi</button> <button id="cc">Chiudi</button>`;m.showModal();$("#cc").onclick=()=>m.close();$("#go").onclick=()=>$("#pp").value===s.pin?(m.close(),admin()):$("#err").textContent="PIN non corretto."};
(async()=>{await boot();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js").catch(()=>{});setInterval(async()=>{if(!s)return;const wk=weekKey();let changed=false;s.kids.forEach(k=>{if(k.weekKey!==wk){k.weekKey=wk;k.weekly=0;k.dailyBonus={};changed=true}});if(s.group.date!==today()){s.group.date=today();s.group.qid=null;s.group.done={};changed=true}if(changed){ensure();await save();render()}},60000)})();