const DB="pokemonQuestV7",STORE="state";
const L=[
["Bulbasaur","Ivysaur","Venusaur",1,2,3],["Charmander","Charmeleon","Charizard",4,5,6],["Squirtle","Wartortle","Blastoise",7,8,9],
["Treecko","Grovyle","Sceptile",252,253,254],["Torchic","Combusken","Blaziken",255,256,257],["Mudkip","Marshtomp","Swampert",258,259,260],
["Chikorita","Bayleef","Meganium",152,153,154],["Cyndaquil","Quilava","Typhlosion",155,156,157],["Totodile","Croconaw","Feraligatr",158,159,160],
["Turtwig","Grotle","Torterra",387,388,389],["Chimchar","Monferno","Infernape",390,391,392],["Piplup","Prinplup","Empoleon",393,394,395]];
const P=[
[3,4,[["🧸","Metti a posto i giochi"],["🪥","Lavati i denti"],["👕","Vestiti da solo"]]],
[5,6,[["🛏️","Metti a posto il pigiama"],["🎒","Prepara una cosa per domani"],["❤️","Aiuta in casa"]]],
[7,8,[["🎒","Prepara zaino e materiale"],["🧹","Riordina ciò che hai usato"],["📚","Leggi per almeno 15 minuti"]]],
[9,10,[["🎒","Prepara zaino e materiale"],["🧹","Riordina ciò che hai usato"],["📚","Leggi per almeno 20 minuti"],["❤️","Aiuta qualcuno senza che te lo chieda"]]],
[11,14,[["🧠","Organizza ciò che serve per domani"],["📚","Leggi per almeno 20 minuti"],["❤️","Aiuta qualcuno senza che te lo chieda"],["⏱️","Gestisci 20 minuti di studio/attività"],["🧹","Svolgi una responsabilità domestica"]]]
];
let db,s,active,tab="quests";
const $=s=>document.querySelector(s);
const img=id=>`https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${String(id).padStart(3,"0")}.png`;
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
const today=()=>new Date().toISOString().slice(0,10);
const lvl=x=>Math.min(30,Math.floor(x/100)+1),st=l=>l>=20?2:l>=10?1:0;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function pool(a){return(P.find(x=>a>=x[0]&&a<=x[1])||P[4])[2]}
function kid(n,a){return{id:id(),name:n,age:a,xp:0,weekly:0,line:0,done:{}}}
function open(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
function get(){return new Promise((ok,no)=>{let r=db.transaction(STORE).objectStore(STORE).get("s");r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function save(){return new Promise((ok,no)=>{let r=db.transaction(STORE,"readwrite").objectStore(STORE).put(s,"s");r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function init(){s={version:7,pin:"1234",kids:[kid("Giuseppe",9),kid("Anna Chiara",7),kid("Elisabetta",5),kid("Miriam",3)],lib:[],assign:{},group:{icon:"🤝",text:"Fate insieme qualcosa di utile in casa",done:false,date:today()},reward:{small:350,big:850}};ensure()}
function ensure(){
 s=s||{}; s.version=7; s.pin=s.pin||"1234"; s.kids=Array.isArray(s.kids)?s.kids:[]; s.lib=Array.isArray(s.lib)?s.lib:[]; s.assign=s.assign&&typeof s.assign==="object"?s.assign:{}; s.reward=s.reward||{small:350,big:850}; s.group=s.group||{icon:"🤝",text:"Fate insieme qualcosa di utile in casa",done:false,date:today()};
 if(!s.kids.length){s.kids=[kid("Giuseppe",9),kid("Anna Chiara",7),kid("Elisabetta",5),kid("Miriam",3)]}
 s.kids.forEach(k=>{k.age=Math.max(1,Math.min(14,Number(k.age)||7));k.xp=Number(k.xp)||0;k.weekly=Number(k.weekly)||0;k.line=Number(k.line)||0;k.done=k.done&&typeof k.done==="object"?k.done:{};s.assign[k.id]=Array.isArray(s.assign[k.id])?s.assign[k.id]:[];pool(Math.max(3,k.age)).forEach(([ic,t])=>{let q=s.lib.find(x=>x.text===t);if(!q){q={id:id(),icon:ic,text:t};s.lib.push(q)}if(!s.assign[k.id].includes(q.id))s.assign[k.id].push(q.id)})});
 if(s.group.date!==today()){s.group.done=false;s.group.date=today()}
}
async function boot(){
 try{await open();s=await get();if(!s)init();ensure();await save();active=s.kids[0]?.id||null;render()}
 catch(e){console.error(e);$("#app").innerHTML=`<div class="card"><h2>⚠️ Errore di caricamento</h2><p>Il browser ha bloccato il salvataggio locale.</p><p class="small">${esc(e?.message||e)}</p><button onclick="location.reload()">Ricarica</button></div>`}
}
function assigned(k){return(s.assign[k.id]||[]).map(x=>s.lib.find(q=>q.id===x)).filter(Boolean)}
function done(k,q){return!!k.done[today()+"|"+q.id]}
function render(){const k=s.kids.find(x=>x.id===active);if(!k){$("#app").innerHTML="";return}let l=lvl(k.xp),z=st(l),p=L[k.line],html=`<div class="kids">${s.kids.map(x=>`<button class="${x.id===active?"active":""}" data-k="${x.id}">${x.age<=6?"👶":"🧒"} ${esc(x.name)}</button>`).join("")}</div><div class="${k.age<=6?"simple":""}"><div class="card hero"><img src="${img(p[3+z])}"><div><div class="row between"><b style="font-size:1.3rem">${p[z]}</b><span class="chip">Lv ${l}</span></div><div class="small">${p[0]} → ${p[1]} → ${p[2]}</div><div class="progress"><div class="bar" style="width:${k.xp%100}%"></div></div><div class="row"><span class="chip">⭐ ${k.xp} XP</span><span class="chip">📅 ${k.weekly} XP</span></div></div></div><div class="tabs"><button class="${tab==="quests"?"active":""}" data-t="quests">📜 Quest</button><button class="${tab==="pokemon"?"active":""}" data-t="pokemon">⚡ Pokémon</button><button class="${tab==="progress"?"active":""}" data-t="progress">🏆 Progressi</button></div>${pane(k)}</div>`;$("#app").innerHTML=html;bind()}
function pane(k){if(tab==="quests")return`<div class="pane active card"><div class="row between"><h2>Quest di oggi</h2><span class="chip">${assigned(k).filter(q=>done(k,q)).length}/${assigned(k).length}</span></div>${assigned(k).map(q=>{let d=done(k,q);return`<div class="quest ${d?"done":""}"><span class="icon">${q.icon}</span><span class="text">${esc(q.text)}</span><button data-q="${q.id}">${d?"↩️ Annulla":"✅ Fatto"}</button></div>`}).join("")}<div class="small">+20 XP per Quest. Completando tutte le Quest: bonus +40 XP.</div></div>`;
if(tab==="pokemon")return`<div class="pane active card"><h2>Scegli il tuo Pokémon</h2><p class="small">Ogni bambino ha una scelta indipendente. Lo stesso Pokémon può essere scelto da più bambini.</p><div class="grid">${L.map((p,i)=>`<div class="poke ${i===k.line?"selected":""}"><img src="${img(p[3])}"><b>${p[0]}</b><div class="small">${p[1]} → ${p[2]}</div><button data-p="${i}">${i===k.line?"✓ Scelto":"Scegli"}</button></div>`).join("")}</div></div>`;
return`<div class="pane active card"><h2>🏆 Progressi</h2><div class="grid"><div class="chip">Livello ${lvl(k.xp)}/30</div><div class="chip">XP totale ${k.xp}</div><div class="chip">XP settimana ${k.weekly}</div></div><p>${lvl(k.xp)<30?`Mancano ${lvl(k.xp)*100-k.xp} XP al prossimo livello.`:"🎉 Livello massimo!"}</p><div class="card">🎁 Piccola ricompensa: <b>${s.reward.small} XP</b> settimanali<br>🏆 Grande ricompensa: <b>${s.reward.big} XP</b> settimanali</div></div>`}
function bind(){document.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{active=b.dataset.k;tab="quests";render()});document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{tab=b.dataset.t;render()});document.querySelectorAll("[data-p]").forEach(b=>b.onclick=async()=>{s.kids.find(k=>k.id===active).line=+b.dataset.p;await save();render()});document.querySelectorAll("[data-q]").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===active),q=s.lib.find(x=>x.id===b.dataset.q),key=today()+"|"+q.id,d=!!k.done[key];if(d){delete k.done[key];k.xp=Math.max(0,k.xp-20);k.weekly=Math.max(0,k.weekly-20)}else{k.done[key]=1;k.xp=Math.min(3000,k.xp+20);k.weekly+=20;if(assigned(k).every(x=>done(k,x))){k.xp=Math.min(3000,k.xp+40);k.weekly+=40}}await save();render()})}
function admin(){let m=$("#modal");m.innerHTML=`<div style="overflow:auto"><div class="row between"><h2>🔐 Area adulti</h2><button id="close">Chiudi</button></div><div class="tabs"><button data-a="kids">👨‍👩‍👧 Bambini</button><button data-a="quests">📜 Quest</button><button data-a="data">💾 Dati</button></div><div id="ab"></div></div>`;m.showModal();$("#close").onclick=()=>m.close();document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>adminPane(b.dataset.a));adminPane("kids")}
function adminPane(t){let b=$("#ab");if(t==="kids")b.innerHTML=`<div class="card"><button id="add">＋ Aggiungi bambino</button></div>${s.kids.map(k=>`<div class="list"><label>Nome</label><input data-n="${k.id}" value="${esc(k.name)}"><label>Età (fino a 6 = modalità semplificata)</label><input data-age="${k.id}" type="number" min="3" max="14" value="${k.age}"><button data-save="${k.id}">Salva</button> <button data-del="${k.id}" style="background:#d63031">Elimina</button></div>`).join("")}`;else if(t==="quests")b.innerHTML=`<div class="card"><button id="newq">＋ Nuova Quest</button></div>${s.lib.map(q=>`<div class="list"><b>${q.icon} ${esc(q.text)}</b><div class="small">Assegnata a: ${s.kids.filter(k=>(s.assign[k.id]||[]).includes(q.id)).map(k=>esc(k.name)).join(", ")||"nessuno"}</div><button data-e="${q.id}">Modifica</button><button data-as="${q.id}">Assegna</button></div>`).join("")}`;else b.innerHTML=`<div class="card"><button id="export">Esporta backup JSON</button><input id="import" type="file" accept=".json"><p class="small">Il backup contiene profili, XP, Pokémon, Quest, assegnazioni e impostazioni.</p><hr><input id="pin" type="password" placeholder="Nuovo PIN"><button id="pinb">Cambia PIN</button></div>`;bindAdmin()}
function bindAdmin(){$("#add")?.addEventListener("click",()=>{let n=prompt("Nome?");if(!n)return;let a=Math.max(1,Math.min(14,+prompt("Età (1-14)?","7")||7)),k=kid(n,a);s.kids.push(k);s.assign[k.id]=[];ensure();save().then(()=>{render();adminPane("kids")})});document.querySelectorAll("[data-save]").forEach(b=>b.onclick=async()=>{let k=s.kids.find(x=>x.id===b.dataset.save);k.name=$(`[data-n="${k.id}"]`).value||k.name;k.age=Math.max(3,Math.min(14,+$(`[data-age="${k.id}"]`).value||7));s.assign[k.id]=[];ensure();await save();render();adminPane("kids")});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(!confirm("Eliminare il profilo?"))return;let i=b.dataset.del;s.kids=s.kids.filter(k=>k.id!==i);delete s.assign[i];active=s.kids[0]?.id;await save();render();adminPane("kids")});$("#newq")?.addEventListener("click",()=>{let t=prompt("Testo Quest");if(!t)return;s.lib.push({id:id(),icon:prompt("Icona","⭐")||"⭐",text:t});save().then(()=>adminPane("quests"))});document.querySelectorAll("[data-e]").forEach(b=>b.onclick=async()=>{let q=s.lib.find(x=>x.id===b.dataset.e),t=prompt("Testo",q.text);if(t===null)return;q.text=t;q.icon=prompt("Icona",q.icon)||q.icon;await save();adminPane("quests");render()});document.querySelectorAll("[data-as]").forEach(b=>b.onclick=()=>{let q=s.lib.find(x=>x.id===b.dataset.as),lines=s.kids.map((k,i)=>`${i+1}. ${k.name}`).join("\\n"),v=prompt(`Assegna "${q.text}" a quali bambini? Numeri separati da virgola.`,lines);if(v===null)return;v.split(",").forEach(x=>{let i=+x.trim()-1;if(i>=0&&i<s.kids.length){s.assign[s.kids[i].id]??=[];if(!s.assign[s.kids[i].id].includes(q.id))s.assign[s.kids[i].id].push(q.id)}});save().then(()=>{adminPane("quests");render()})});$("#export")?.addEventListener("click",()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:"application/json"}));a.download="pokemon-quest-backup.json";a.click()});$("#import")?.addEventListener("change",async e=>{let f=e.target.files[0];if(!f)return;try{s=JSON.parse(await f.text());ensure();await save();active=s.kids[0]?.id;render();alert("Backup ripristinato")}catch{alert("Backup non valido")}});$("#pinb")?.addEventListener("click",async()=>{let p=$("#pin").value;if(p.length<4)return alert("PIN troppo corto");s.pin=p;await save();alert("PIN cambiato")})}
$("#adult").onclick=()=>{let m=$("#modal");m.innerHTML=`<h2>🔐 Area adulti</h2><input id="pp" type="password" inputmode="numeric" placeholder="PIN"><p id="err" class="small"></p><button id="go">Accedi</button> <button id="cc">Chiudi</button>`;m.showModal();$("#cc").onclick=()=>m.close();$("#go").onclick=()=>$("#pp").value===s.pin?(m.close(),admin()):$("#err").textContent="PIN non corretto."};
(async()=>{await boot();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js").catch(()=>{})})();